version: "3.5"
services:
 annotation-ingester:
    build: .
    shm_size : 128mb
    restart: always
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro
    network_mode: host
    command: "/app/run.sh"
    