source:
  es:
    hosts: ["http://127.0.0.1:9200"]
    credentials:
      username : "elastic"
      password : "admin"
      use-api-key : False
    index-name: 'medical_reports_text'
    extra-params:
      use-ssl: False
      verify-certs: False
    security:
      ca-certs-path: "/app/config/root-ca.pem"
      client-cert-path: "/app/config/client.pem"
      client-key-path: "/app/config/client.key"

sink:
  es:
    hosts: ["http://127.0.0.1:9200"]
    credentials:
      username : "elastic"
      password : "admin"
      use-api-key : False
    index-name: 'medical_reports_text_annotations_gate_nlp'
    extra-params:
      use-ssl: False
      verify-certs: False
    security:
      ca-certs-path: "/app/config/root-ca.pem"
      client-cert-path: "/app/config/client.pem"
      client-key-path: "/app/config/client.key"

nlp-service:
  endpoint-url: ['http://localhost:5555/api/process']
  endpoint-request-mode : ''
  use-bulk-indexing : True
  annotation-response:
    dict-key : "annotations"
    result-key : "result"
  credentials :  
    username : ""
    password : ""

mapping:
  index-ingest-mode:
    same-index: False
    use-nested-objects: False
    es-nested-object-schema-mapping : ""
  source:
    text-field: 'document'
    docid-field: '_id'
    persist-fields:
     - '_id'
    batch:
      date-field: 'dct'
      date-format: 'yyyy-MM-dd'
      python-date-format: '%Y-%m-%d' 
      interval: 30
      date-start: '1999-01-01'
      date-end: '2021-02-01'
      threads: 8
  sink:
    split-index-by-field: '' # 'type', splits into different indices with separate prefix
  nlp:
    skip-processed-doc-check: True
    annotation-id-field: 'id'

# DEBUG = 10 , INFO = 20, WARNING = 30, ERROR = 40, CRITICAL = 50
logging-level: "20"

