source:
  es:
    hosts: ["https://cogstack:cogstack@localhost:9200"]
    index-name: 'cogstack_observations_view'
    security:
      ca-certs-path: "/app/config/root-ca.pem"
      client-cert-path: "/app/config/client.pem"
      client-key-path: "/app/config/client.key"

sink:
  es:
    hosts: ["http://cogstack:cogstack@localhost:9200"]
    index-name: 'cogstack_atomic_annotations'
    security:
      ca-certs-path: "/app/config/root-ca.pem"
      client-cert-path: "/app/config/client.pem"
      client-key-path: "/app/config/client.key"

nlp-service:
  endpoint-url: 'http://localhost:8095/api/process'

mapping:
  source:
    text-field: 'document_content'
    docid-field: 'encounter_id'
    persist-fields:
      - 'encounter_id'
      - 'patient_id'
      - 'encounter_start'
      - 'encounter_end'
    batch:
      date-field: 'encounter_start'
      date-format: 'yyyy-MM-dd'
      date-start: '2010-01-01'
      date-end: '2018-06-01'
      threads: 8
  sink:
    split-index-by-field: 'type'
  nlp:
    skip-processed-doc-check: 'true'
    annotation-id-field: 'id'
