source:
  es:
    hosts: ["http://elastic:admin@localhost:9200"]
    index-name: 'sample_observations_view'
    extra-params:
      use-ssl: False
      verify-certs: False
    security:
      ca-certs-path: "/app/config/root-ca.pem"
      client-cert-path: "/app/config/client.pem"
      client-key-path: "/app/config/client.key"

sink:
  es:
    hosts: ["http://elastic:admin@localhost:9200"]
    index-name: 'cogstack_atomic_annotations'
    extra-params:
      use-ssl: False
      verify-certs: False
    security:
      ca-certs-path: "/app/config/root-ca.pem"
      client-cert-path: "/app/config/client.pem"
      client-key-path: "/app/config/client.key"

nlp-service:
  endpoint-url: 'http://localhost:5555/api/process'
  annotation-response:
    dict-key : "annotations"
    result-key : "result"

mapping:
  use-bulk-indexing : True
  index-ingest-mode:
    same-index: True
    use-nested-objects: True
  
  source:
    text-field: 'encounter_document'
    docid-field: 'encounter_id'
    persist-fields:
      - 'encounter_id'
    batch:
      date-field: 'encounter_start'
      date-format: 'yyyy-MM-dd'
      python-date-format: '%Y-%m-%d' 
      interval: 7
      date-start: '1999-01-01'
      date-end: '2021-02-01'
      threads: 8
  sink:
    split-index-by-field: ''

  nlp:
    skip-processed-doc-check: 'true'
    annotation-id-field: 'id'

# DEBUG = 10 , INFO = 20, WARNING = 30, ERROR = 40, CRITICAL = 50
logging-level: "20"